export const GETDATA_LOADING='GETDATA_LOADING';
export const GETDATA_SUCCESS='GETDATA_SUCCESS';
export const GETDATA_ERROR='GETDATA_ERROR';


export const GETDATA2_LOADING='GETDATA2_LOADING';
export const GETDATA2_SUCCESS='GETDATA2_SUCCESS';
export const GETDATA2_ERROR='GETDATA2_ERROR';

export const GOAL_DATA='GOAL_DATA';

export const TUTOR_DATA='TUTOR_DATA'

export const SHOW_SIDE='SHOW_SIDE'

export const PHONE_NUMBER='PHONE_NUMBER'